// Code generated by swagger-doc. DO NOT EDIT.

package v1beta1

func (OvirtVolumePopulator) SwaggerDoc() map[string]string {
	return map[string]string{
		"":       "OvirtVolumePopulator is the CR used to populator a volume from an oVirt disk\n+genclient\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+k8s:openapi-gen=true\n+kubebuilder:resource:shortName={ovvp,ovvps}",
		"status": "+optional",
	}
}

func (OvirtVolumePopulatorSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"transferNetwork": "The network attachment definition that should be used for disk transfer.",
	}
}

func (OvirtVolumePopulatorStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"progress": "+optional",
	}
}

func (OvirtVolumePopulatorList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "OvirtVolumePopulatorList contains a list of OvirtVolumePopulators\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
	}
}

func (OpenstackVolumePopulator) SwaggerDoc() map[string]string {
	return map[string]string{
		"":       "+genclient\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+k8s:openapi-gen=true\n+kubebuilder:resource:shortName={osvp,osvps}",
		"status": "+optional",
	}
}

func (OpenstackVolumePopulatorSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"transferNetwork": "The network attachment definition that should be used for disk transfer.",
	}
}

func (OpenstackVolumePopulatorStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"progress": "+optional",
	}
}

func (OpenstackVolumePopulatorList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
	}
}
