// Code generated by swagger-doc. DO NOT EDIT.

package v1beta1

func (OvirtVolumePopulator) SwaggerDoc() map[string]string {
	return map[string]string{
		"":       "+genclient\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+k8s:openapi-gen=true\n+kubebuilder:resource:shortName={ovvp,ovvps}\nOvirtVolumePopulator is the CR used to populator a volume from an oVirt disk",
		"status": "+optional",
	}
}

func (OvirtVolumePopulatorSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                "OvirtVolumePopulatorSpec is the spec of the OvirtVolumePopulator CR",
		"transferNetwork": "The network attachment definition that should be used for disk transfer.",
	}
}

func (OvirtVolumePopulatorStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"":         "OvirtVolumePopulatorStatus is the status of the OvirtVolumePopulator CR",
		"progress": "+optional",
	}
}

func (OvirtVolumePopulatorList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "OvirtVolumePopulatorList contains a list of OvirtVolumePopulators\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\nOvirtVolumePopulatorList is the CR used to populator a volume from an oVirt disk",
	}
}

func (OpenstackVolumePopulator) SwaggerDoc() map[string]string {
	return map[string]string{
		"":       "+genclient\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+k8s:openapi-gen=true\n+kubebuilder:resource:shortName={osvp,osvps}\nOpenstackVolumePopulator is the CR used to populator a volume from an Openstack image",
		"status": "+optional",
	}
}

func (OpenstackVolumePopulatorSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                "OpenstackVolumePopulatorSpec is the spec of the OpenstackVolumePopulator CR",
		"transferNetwork": "The network attachment definition that should be used for disk transfer.",
	}
}

func (OpenstackVolumePopulatorStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"":         "OpenstackVolumePopulatorStatus is the status of the OpenstackVolumePopulator CR",
		"progress": "+optional",
	}
}

func (OpenstackVolumePopulatorList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\nOpenstackVolumePopulatorList contains a list of OpenstackVolumePopulators",
	}
}
