linters:
  enable:
  - errname
  - errorlint
  - ginkgolinter
  - goimports
  - misspell
  - nakedret
  - unconvert

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  errorlint:
    # We want to allow for usage of %v to avoid leaking implementation details
    errorf: false
  ginkgolinter:
    forbid-focus-container: true
  nakedret:
    max-func-lines: 0
