/*
Copyright 2018 The CDI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubevirt.io/containerized-data-importer/pkg/apis/cdicontroller/v1alpha1"
	scheme "kubevirt.io/containerized-data-importer/pkg/client/clientset/versioned/scheme"
)

// UploadTokensGetter has a method to return a UploadTokenInterface.
// A group's client should implement this interface.
type UploadTokensGetter interface {
	UploadTokens(namespace string) UploadTokenInterface
}

// UploadTokenInterface has methods to work with UploadToken resources.
type UploadTokenInterface interface {
	Create(*v1alpha1.UploadToken) (*v1alpha1.UploadToken, error)
	Update(*v1alpha1.UploadToken) (*v1alpha1.UploadToken, error)
	UpdateStatus(*v1alpha1.UploadToken) (*v1alpha1.UploadToken, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.UploadToken, error)
	List(opts v1.ListOptions) (*v1alpha1.UploadTokenList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.UploadToken, err error)
	UploadTokenExpansion
}

// uploadTokens implements UploadTokenInterface
type uploadTokens struct {
	client rest.Interface
	ns     string
}

// newUploadTokens returns a UploadTokens
func newUploadTokens(c *CdiV1alpha1Client, namespace string) *uploadTokens {
	return &uploadTokens{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the uploadToken, and returns the corresponding uploadToken object, and an error if there is any.
func (c *uploadTokens) Get(name string, options v1.GetOptions) (result *v1alpha1.UploadToken, err error) {
	result = &v1alpha1.UploadToken{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("uploadtokens").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of UploadTokens that match those selectors.
func (c *uploadTokens) List(opts v1.ListOptions) (result *v1alpha1.UploadTokenList, err error) {
	result = &v1alpha1.UploadTokenList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("uploadtokens").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested uploadTokens.
func (c *uploadTokens) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("uploadtokens").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a uploadToken and creates it.  Returns the server's representation of the uploadToken, and an error, if there is any.
func (c *uploadTokens) Create(uploadToken *v1alpha1.UploadToken) (result *v1alpha1.UploadToken, err error) {
	result = &v1alpha1.UploadToken{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("uploadtokens").
		Body(uploadToken).
		Do().
		Into(result)
	return
}

// Update takes the representation of a uploadToken and updates it. Returns the server's representation of the uploadToken, and an error, if there is any.
func (c *uploadTokens) Update(uploadToken *v1alpha1.UploadToken) (result *v1alpha1.UploadToken, err error) {
	result = &v1alpha1.UploadToken{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("uploadtokens").
		Name(uploadToken.Name).
		Body(uploadToken).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *uploadTokens) UpdateStatus(uploadToken *v1alpha1.UploadToken) (result *v1alpha1.UploadToken, err error) {
	result = &v1alpha1.UploadToken{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("uploadtokens").
		Name(uploadToken.Name).
		SubResource("status").
		Body(uploadToken).
		Do().
		Into(result)
	return
}

// Delete takes name of the uploadToken and deletes it. Returns an error if one occurs.
func (c *uploadTokens) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("uploadtokens").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *uploadTokens) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("uploadtokens").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched uploadToken.
func (c *uploadTokens) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.UploadToken, err error) {
	result = &v1alpha1.UploadToken{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("uploadtokens").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
