apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: clone-block-datavolume
spec:
  source:
    pvc:
      namespace: default
      name: import-kubevirt-block-datavolume
  storage:
    volumeMode: Block
