apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: import-kubevirt-block-datavolume
spec:
  source:
    http:
      url: "http://distro.ibiblio.org/tinycorelinux/9.x/x86/release/Core-current.iso"
  pvc:
    # Optional: Set the storage class or omit to accept the default
    storageClassName: local
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
