# This example assumes you are using a default storage class
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: my-data-volume
spec:
  source:
      gcs:
         url: "gs://bucket/file.img"
         secretRef: "gcs-secret"
  storage:
    resources:
      requests:
        storage: 500Mi
