apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: upload-block-datavolume
spec:
  source:
      upload: {}
  pvc:
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
