FROM docker.io/kubevirt/kubevirt-cdi-bazel-builder:0.0.8 AS builder
WORKDIR /go/src/github.com/kubevirt.io/containerized-data-importer
COPY . .

ENV KUBEVIRT_RUN_UNNESTED=true

RUN source /etc/profile.d/gimme.sh && \
    export GOPATH="/go" && \
    ./hack/ci/build.sh

ENTRYPOINT [ "/entrypoint-bazel.sh" ]
CMD ["./hack/ci/test.sh"]
