load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "kubevirt.io/containerized-data-importer/tools/cdi-env-extractor",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "cdi-env-extractor",
    embed = [":go_default_library"],
    pure = "on",
    visibility = ["//visibility:public"],
)

pkg_tar(
    name = "cdi-env-extractor-bin",
    srcs = [":cdi-env-extractor"],
    extension = "tar.gz",
    package_dir = "/usr/bin/",
    visibility = ["//visibility:public"],
)
