/*
Copyright 2018 The CDI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubevirt.io/containerized-data-importer/pkg/apis/cdicontroller/v1alpha1"
)

// FakeUploadTokens implements UploadTokenInterface
type FakeUploadTokens struct {
	Fake *FakeCdiV1alpha1
	ns   string
}

var uploadtokensResource = schema.GroupVersionResource{Group: "cdi.kubevirt.io", Version: "v1alpha1", Resource: "uploadtokens"}

var uploadtokensKind = schema.GroupVersionKind{Group: "cdi.kubevirt.io", Version: "v1alpha1", Kind: "UploadToken"}

// Get takes name of the uploadToken, and returns the corresponding uploadToken object, and an error if there is any.
func (c *FakeUploadTokens) Get(name string, options v1.GetOptions) (result *v1alpha1.UploadToken, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(uploadtokensResource, c.ns, name), &v1alpha1.UploadToken{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UploadToken), err
}

// List takes label and field selectors, and returns the list of UploadTokens that match those selectors.
func (c *FakeUploadTokens) List(opts v1.ListOptions) (result *v1alpha1.UploadTokenList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(uploadtokensResource, uploadtokensKind, c.ns, opts), &v1alpha1.UploadTokenList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.UploadTokenList{}
	for _, item := range obj.(*v1alpha1.UploadTokenList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested uploadTokens.
func (c *FakeUploadTokens) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(uploadtokensResource, c.ns, opts))

}

// Create takes the representation of a uploadToken and creates it.  Returns the server's representation of the uploadToken, and an error, if there is any.
func (c *FakeUploadTokens) Create(uploadToken *v1alpha1.UploadToken) (result *v1alpha1.UploadToken, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(uploadtokensResource, c.ns, uploadToken), &v1alpha1.UploadToken{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UploadToken), err
}

// Update takes the representation of a uploadToken and updates it. Returns the server's representation of the uploadToken, and an error, if there is any.
func (c *FakeUploadTokens) Update(uploadToken *v1alpha1.UploadToken) (result *v1alpha1.UploadToken, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(uploadtokensResource, c.ns, uploadToken), &v1alpha1.UploadToken{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UploadToken), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeUploadTokens) UpdateStatus(uploadToken *v1alpha1.UploadToken) (*v1alpha1.UploadToken, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(uploadtokensResource, "status", c.ns, uploadToken), &v1alpha1.UploadToken{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UploadToken), err
}

// Delete takes name of the uploadToken and deletes it. Returns an error if one occurs.
func (c *FakeUploadTokens) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(uploadtokensResource, c.ns, name), &v1alpha1.UploadToken{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUploadTokens) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(uploadtokensResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.UploadTokenList{})
	return err
}

// Patch applies the patch and returns the patched uploadToken.
func (c *FakeUploadTokens) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.UploadToken, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(uploadtokensResource, c.ns, name, data, subresources...), &v1alpha1.UploadToken{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UploadToken), err
}
