apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disks
spec:
  storageClassDevices:
    - storageClassName: local-sc
      volumeMode: Filesystem
      fsType: ext4
      devicePaths:
        - /mnt/local-storage/local-sc
