  on: ["push","pull_request"]

  name: Test Coveralls

  jobs:

    build:
      name: Build
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: make test-coverage
        run: |
          make goveralls

      - name: Coveralls
        uses: coverallsapp/github-action@master
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-token: ${{ secrets.github_token }}
