name: Build x86 and arm Image

on:
  pull_request:
    branches:
      - ecx-*
  push:
    branches:
      - ecx-*

env:
  VERSION: v1.41.0.1

jobs:
  build_x86:
    name: Build x86
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.7
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          export DOCKER_TAG=$VERSION-amd64
          export DOCKER_PREFIX=${{ secrets.DOCKER_USERNAME }}
          export BUILD_ARCH=x86_64
          make bazel-build-images
          make bazel-push-images
  build_arm:
    name: Build arm
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.7
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: |
          export DOCKER_TAG=$VERSION-arm64
          export DOCKER_PREFIX=${{ secrets.DOCKER_USERNAME }}
          export BUILD_ARCH=crossbuild-aarch64
          make bazel-build-images
          make bazel-push-images
  push_manifest_list:
    runs-on: ubuntu-18.04
    name: push manifest list
    needs: [ build_x86, build_arm]
    strategy: # 矩阵策略
      matrix:
        docekr_image: [cdi-controller,cdi-importer,cdi-cloner,cdi-uploadproxy,cdi-apiserver,cdi-uploadserver,cdi-operator]

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create docker manifest and Push the new manifest file
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          export DOCKER_PREFIX_TAG=$VERSION
          export DOCKER_PREFIX=$DOCKER_USERNAME
          docker manifest create $DOCKER_USERNAME/${{ matrix.docekr_image }}:$DOCKER_PREFIX_TAG $DOCKER_USERNAME/${{ matrix.docekr_image }}:$DOCKER_PREFIX_TAG-amd64 $DOCKER_USERNAME/${{ matrix.docekr_image }}:$DOCKER_PREFIX_TAG-arm64
          docker manifest push $DOCKER_USERNAME/${{ matrix.docekr_image }}:$DOCKER_PREFIX_TAG
